#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 󰈹     6 7 8

$HOME/.config/polybar/launch.sh

bspc config border_width         3.5
bspc config window_gap          22
bspc config focused_border_color "#3dd8e3"
bspc config normal_border_color "#2b9ea6"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
