format = '''
$directory
'''

right_format = """
$cmd_duration\
"""

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow) "

[directory]
style = "bg:#181A1F;fg:#81a1c1"
format = '[ $path ](fg:#81a1c1 bg:#181A1F) '
