#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 󰈹     6 7 8

$HOME/startlaunch.sh
$HOME/.config/polybar/launch.sh

bspc config border_width 0
bspc config window_gap 17
#bspc config focused_border_color "#3dd8e3"
#bspc config normal_border_color "#2b9ea6"

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true

bspc rule -a firefox desktop='󰈹'
