#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

#bspc monitor -d 󰈹    
bspc monitor -d 1 2 3 4 5

$HOME/startlaunch.sh
$HOME/.config/polybar/launch.sh

bspc config border_width 3.5
bspc config window_gap 12
bspc config normal_border_color "#2b9ea6"
bspc config focused_border_color "#2b9ea6"

bspc config split_ratio 0.51
bspc config borderless_monocle false
bspc config gapless_monocle true

bspc rule -a firefox desktop='1'
